name: Python Control Structures Assignment

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test cases
        run: |
          python3 tests/test_assignment.py TestControlStructures.test_while_loop
          python3 tests/test_assignment.py TestControlStructures.test_for_loop_continue
          python3 tests/test_assignment.py TestControlStructures.test_if_else
          python3 tests/test_assignment.py TestControlStructures.test_nested_loops
